sudo: false
language: node_js
cache:
  directories:
  - node_modules # NPM packages
node_js:
- 6
addons:
  ssh_known_hosts: coworks.cl
before_deploy:
- eval "$(ssh-agent -s)"
- mv $TRAVIS_BUILD_DIR/deploy_rsa /tmp/deploy_rsa
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_ddfaf0389a7e_key -iv $encrypted_ddfaf0389a7e_iv
  -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d
after_deploy:
- rm deploy_rsa
after_script:
- echo "--------- DEPLOY DONE! ---------"
